{% set name = "doit" %}
{% set version = "0.37.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d3c72e0e46a8fa1ddabea8f830762402dee090caf33c30c2295ac7010db8f09c

build:
  number: 0
  skip: true  # [py<310]
  entry_points:
    - doit = doit.__main__:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --no-cache-dir

requirements:
  host:
    - python
    - pip
    - setuptools >=68.0
  run:
    - python
  run_constrained:
    - tomli  # [py<311]

test:
  source_files:
    - tests
    - dodo.py
  imports:
    - doit
  requires:
    - pip
    - pytest
    - pyflakes
  commands:
    - pip check
    - doit --help
    - pytest -v tests

about:
  home: https://pydoit.org
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: doit - Automation Tool
  description: |
    doit is a task management & automation tool.
    doit comes from the idea of bringing the power of build-tools to execute
    any kind of **task**
    doit is a modern open-source build-tool written in python designed to be
    simple to use and flexible to deal with complex work-flows.
    It is specially suitable for building and managing custom work-flows where
    there is no out-of-the-box solution available. 
    doit has been successfully used on: systems test/integration automation,
    scientific computational pipelines, content generation, configuration
    management, etc.
  doc_url: https://pydoit.org/contents.html
  dev_url: https://github.com/pydoit/doit

extra:
  recipe-maintainers:
    - pbronez
