travis:
  secure:
    BINSTAR_TOKEN: HjFM0z5VC2kfhdhPPzKvaE3JnsTe0WqczyEK9w1IrS5Lk5SNFOSvIulxSZSjww07nIolRHv3Jrq4WQesGZbpu1JZDUA3lkCisROYMSsnbivMhPIHcEFvg2BVtv/+UZekxddNnON7Dzq0Gkyd8rkuAC7kJzgzy5JCfZUIj3kTiVmTucjUXUqkch06rayrlpj8/hmyWsPU+ZA+y3G0GntKwW2UMcmgXM2TQd2jdo0r9tGoYqhkstdNDY1PHYPqwJYVbfn3Q8OuxV6BSVAixMj3Wb+blMutMRr+6AwLQJoscwBWD6Olq1VORu1HfBs5xYM5nW6abwqs62xxJHQomgjxlTKoLPnPEtFRyGAH2IM36u2sFJjnrnBDWcp6yfomdthsBDwQoRS2JpzB8o6FaGjGDgQMzRUx0Ek7VrcsTK6k9RiLi47EofBt1oSlDtqA8M3PTu/RE3MpcgAEDX9JXdMRk7BACyIM2WkS6wWm1Cuvb8TXggxTsHMtCfw1l98ULwdshU9ONwfnSflmXNwlEiCnKgoJX7MQqJVpVbU0BnTOolwQk+4CdbLqCmxeyZqL3Kda37tvbCGdYcp3Klde+UyJryqhGWk4B5srbHxyhusQDLDHKD+MvF6I1qjqGYkGyCtj5DQfX0zqrNdL5MPuMbj8NzUgxEiuBLOBKbYV17stEhE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
